version: '3.5'
services:
  #Service for nameserver
  namesrv:
    image: registry.cn-beijing.aliyuncs.com/jenphyjohn/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/opt/logs
      - ./data/namesrv/store:/opt/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms256M -Xmx256M -Xmn128m"
    command: ["sh","mqnamesrv"]

  #Service for broker
  broker:
    image: registry.cn-beijing.aliyuncs.com/jenphyjohn/rocketmq
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
        JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    volumes:
      - ./data/broker/logs:/opt/logs
      - ./data/broker/store:/opt/store
      - ./data/broker/conf/broker.conf:/etc/rocketmq-ROCKETMQ_VERSION/broker.conf
    command: ["sh","mqbroker","-c","/etc/rocketmq-ROCKETMQ_VERSION/broker.conf","-n","namesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - namesrv

  #Service for rocketmq-console
  console:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8849:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - namesrv
